<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>dk.sdu.cbse</groupId><artifactId>asteroids-final</artifactId><version>1.0-SNAPSHOT</version></parent>
    <artifactId>asteroids-distribution</artifactId>
    <packaging>pom</packaging>
    <dependencies>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>dk.sdu.cbse.player</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>dk.sdu.cbse.enemy</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>dk.sdu.cbse.asteroids</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>dk.sdu.cbse.weapon</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>dk.sdu.cbse.collision</artifactId><version>${project.version}</version></dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <filesets>
                        <fileset><directory>${project.basedir}/../plugins</directory><includes><include>*.jar</include></includes></fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.1</version>
                <executions>
                    <execution>
                        <id>copy-plugins</id>
                        <phase>package</phase>
                        <goals><goal>copy-dependencies</goal></goals>
                        <configuration>
                            <outputDirectory>${project.basedir}/../plugins</outputDirectory>
                            <includeArtifactIds>dk.sdu.cbse.player,dk.sdu.cbse.enemy,dk.sdu.cbse.asteroids,dk.sdu.cbse.weapon,dk.sdu.cbse.collision</includeArtifactIds>
                            <excludeTransitive>true</excludeTransitive>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
